/**
 * Namen voor de tokens uit src/theme.css. Hier staan geen waarden — alleen
 * verwijzingen — zodat er precies één plek is waar het ontwerp verandert.
 *
 * @type {import('tailwindcss').Config}
 */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        ink: 'var(--ink)',
        'ink-status': 'var(--ink-status)',
        'ink-quote': 'var(--ink-quote)',
        muted: 'var(--muted)',
        dim: 'var(--dim)',
        faint: 'var(--faint)',
        accent: 'var(--accent)',
        'accent-wash': 'var(--accent-wash)',
        rule: 'var(--rule)',
        'rule-faint': 'var(--rule-faint)',
        'rule-strong': 'var(--rule-strong)',
        'field-border': 'var(--field-border)',
        'field-bg': 'var(--field-bg)',
        'chip-border': 'var(--chip-border)',
        'checkbox-border': 'var(--checkbox-border)',
        'checkbox-idle': 'var(--checkbox-border-idle)',
        'on-accent': 'var(--on-accent)',
        'primary-bg': 'var(--primary-bg)',
        'primary-ink': 'var(--primary-ink)',
      },
      fontFamily: {
        serif: 'var(--font-serif)',
        sans: 'var(--font-sans)',
      },
      fontSize: {
        display: 'var(--text-display)',
        exercise: 'var(--text-exercise)',
        input: 'var(--text-input)',
        'screen-title': 'var(--text-screen-title)',
        timer: 'var(--text-timer)',
        stepper: 'var(--text-stepper)',
        stat: 'var(--text-stat)',
        'week-stat': 'var(--text-week-stat)',
        'set-value': 'var(--text-set-value)',
        lead: 'var(--text-lead)',
        'day-number': 'var(--text-day-number)',
        quote: 'var(--text-quote)',
        button: 'var(--text-button)',
        note: 'var(--text-note)',
        list: 'var(--text-list)',
        body: 'var(--text-body)',
        label: 'var(--text-label)',
        meta: 'var(--text-meta)',
        caps: 'var(--text-caps)',
        'caps-lg': 'var(--text-caps-lg)',
      },
      letterSpacing: {
        caps: 'var(--tracking-caps)',
        'caps-wide': 'var(--tracking-caps-wide)',
        'caps-tight': 'var(--tracking-caps-tight)',
        'caps-day': 'var(--tracking-caps-day)',
        display: 'var(--tracking-display)',
      },
      lineHeight: {
        quote: 'var(--leading-quote)',
        exercise: 'var(--leading-exercise)',
        secondary: 'var(--leading-secondary)',
        meta: 'var(--leading-meta)',
      },
      spacing: {
        gutter: 'var(--gutter)',
        block: 'var(--gap-block)',
        'in-block': 'var(--gap-in-block)',
        tight: 'var(--gap-tight)',
        row: 'var(--row-pad-y)',
        'today-row': 'var(--today-row-pad-y)',
        bleed: 'var(--today-row-bleed)',
        primary: 'var(--primary-pad-y)',
        'nav-top': 'var(--nav-pad-top)',
        'nav-bottom': 'var(--nav-pad-bottom)',
        stepper: 'var(--stepper-gap)',
        'stat-y': 'var(--pad-stat-y)',
        stat: 'var(--gap-stat)',
        'stat-x': 'var(--pad-stat-x)',
        'week-stat-x': 'var(--pad-week-stat-x)',
        segment: 'var(--gap-segment)',
        'segment-y': 'var(--pad-segment-y)',
        'checkin-row': 'var(--gap-checkin-row)',
        'checkin-label': 'var(--gap-checkin-label)',
        column: 'var(--gap-column)',
        meta: 'var(--gap-meta)',
        action: 'var(--gap-action)',
        'action-y': 'var(--pad-action-y)',
        'session-bottom': 'var(--pad-session-bottom)',
        timer: 'var(--gap-timer)',
        progress: 'var(--gap-progress)',
      },
      width: {
        secondary: 'var(--secondary-width)',
        arrow: 'var(--arrow-width)',
        'stepper-btn': 'var(--stepper-button)',
        checkbox: 'var(--checkbox-size)',
        'day-col': 'var(--day-column)',
        'set-label': 'var(--set-label)',
        pace: 'var(--pace-column)',
        'checkin-label': 'var(--checkin-label)',
      },
      height: {
        stepper: 'var(--stepper-height)',
        checkbox: 'var(--checkbox-size)',
        bar: 'var(--bar-height)',
        progress: 'var(--progress-height)',
      },
      minHeight: {
        tap: 'var(--tap-min)',
        stepper: 'var(--stepper-height)',
      },
      minWidth: {
        'number-field': 'var(--input-min-width)',
      },
      maxWidth: {
        content: 'var(--content-max)',
      },
      borderWidth: {
        // 'hair' en niet 'rule': anders botst de breedte border-rule met de kleur border-rule
        hair: 'var(--rule-width)',
        accent: 'var(--accent-inset)',
      },
      transitionDuration: {
        color: 'var(--duration-color)',
        check: 'var(--duration-check)',
      },
    },
  },
  plugins: [],
}
